const CategoryActionType = {
    
    GET_ALL_PRODUCT_LIST:'GET_ALL_PRODUCT_LIST',
    ADD_TO_CART_PRODUCT:'ADD_TO_CART_PRODUCT',
    SET_LOADING_TRUE:'SET_LOADING_TRUE',
    SET_LOADING_FALSE:'SET_LOADING_FALSE',
    SET_ERROR_TRUE:'SET_ERROR_TRUE',
    SET_ERROR_FALSE:'SET_ERROR_FALSE',

}


export default CategoryActionType;